name: running commands using github actions
on: 
 push:
   branches:
     - main
  
jobs: 
  init:
   runs-on: self-hosted
   steps:
     - name: whoami
       run: echo $(whoami)
     - name: SystemInfo
       run: echo $(systeminfo)
     
 
